nettisivu/index/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'index'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^distrot$', views.distro, name='distrot'),
    url(r'^lisätietoa$', views.toinensivu, name='toinensivu')
]

nettisivu/nettisivu/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('index.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nettisivu/index/models.py
from django.db import models

# Create your models here.

class Distro(models.Model):
    nimi = models.CharField(max_length=50)
    kuvaus = models.TextField(max_length=2500)
    kuva = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.nimi

class Artikkeli(models.Model):
    otsikko = models.CharField(max_length=50)
    teksti = models.TextField(max_length=5000)
    kuva = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.otsikko

class Postaus(models.Model):
    nimi = models.CharField(max_length=50)
    postaus = models.TextField(max_length=250)
    päivämäärä = models.DateTimeField()

nettisivu/index/forms.py
from django import forms

class PostForm(forms.Form):
    nimi = forms.CharField(max_length=50)
    postaus = forms.CharField(max_length=250)

nettisivu/index/views.py
from django.shortcuts import render, HttpResponse
from .models import Distro, Artikkeli
from index.forms import PostForm

def index(req):
    return render(req, "index/index.html")

def distro(req):
    distrot = Distro.objects.all()
    return render(req, "index/distrot.html", {'distrot': distrot})

def toinensivu(req):
    artikkelit = Artikkeli.objects.all()
    return render(req, "index/toinensivu.html", {'artikkelit': artikkelit})

nettisivu/index/templates/index/base.html
<html>
<head>
    {% load staticfiles %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
	<script src="{% static 'js/script.js' %}"></script>
	<title>koulutyö</title>
</head>
<body>
	<header>	
		<nav>
            <h1>Koulutyö</h1>
			<ul>
				<li><a href="{% url 'index:index' %}">Etusivu</a></li>
				<li><a href="{% url 'index:toinensivu' %}">Lisätietoa linuxista</a></li>
				<li><a href="{% url 'index:distrot' %}">Jakeluita</a></li>
			</ul>
		</nav>
	</header>
	<a href="#" id="nappi">ylös</a>
    <div class="asd">
    {% block content %}

    {% endblock %}
    </div>
</body>
</html>

nettisivu/index/templates/index/distrot.html
{% extends 'index/base.html' %}

{% block content %}
    <div id="distro-header">
        <h1>Suosittuja linux-jakeluita</h1>
        <ul id="distrolista">
            {% for distro in distrot %}
                <li><a href="#{{ distro.nimi }}"> {{ distro.nimi }}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% for distro in distrot %}
    <div class="distro">
        <img  id="{{ distro.nimi }}" src="{{ distro.kuva.url }}" style="width: 200px">
        <h3 id="nimi">{{ distro.nimi }}</h3> <br>
        <p id="kuvaus">{{ distro.kuvaus }}</p>
    </div>
    {% endfor %}
    
{% endblock %}

nettisivu/index/templates/index/index.html
{% extends 'index/base.html' %}

{% block content %}
    <div class="box">
        <img src="../../static/img/tux.png"/>
        <div class="text">
        <h2>Mikä Linux on?</h2>
        <p>Linux on käyttöjärjestelmä niinkuin windows. Linux on vapaata ohjelmistoa joten kuka vaan saa ladata linuxin, muokata sitä ja tehdä sillä mitä haluaa. 
	 Näitä eri muokattuja versioita sanotaan jakeluiksi. Linux voi tarkoittaa käyttöjärjestelmän ydintä joka linux alunperin oli tai sitten linux-käyttöjärjestelmää mistä tässä tekstissä puhutaan. </p>
        </div>
    </div>

    <div class="historia">
        <div class="text">
            <h2>Linuxin synty</h2>
            <p class="text2">Vuonna 1991 suomenruotsalainen tietotekniikka-asiantuntija Linus Torvalds ei ollut tyytyväinen Minix-käyttöjärjestelmän pääte-emulaattoriin joten hän päätti tehdä uuden itse. Tästä päätteestä lopulta muodostui käyttöjärjestelmän ydin joka sai myöhemmin nimekseen linux. 
            </p>
        </div>
    </div>

{% endblock %}

nettisivu/index/templates/index/toinensivu.html
{% extends 'index/base.html' %}

{% block content %}

    <nav id="artikkeli-navigaatio">
    <ul>
        {% for artikkeli in artikkelit %}
        <li><a href="#{{ artikkeli.otsikko }}">{{ artikkeli.otsikko }}</a></li>
        {% endfor %}
    </ul>
    </nav>

    <!-- <h2>Jakelut</h2>
    <p>Linux-käyttöjärjestelmä on aviointa lähdekoodia joten kuka vaan voi ladata linuxin ja muokata siitä sellaisen kuin haluaa.
        Nämä eri "muokkaukset" linuxista ovat jakeluita. Tunnnettuja jakeluita voit katsoa <a href="{% url 'index:distrot' %}">täältä</a>.
        Eri jakelut tulevat eri työpöytäympäristöillä ja muilla eri ohjelmistoilla. Jotkut jakelut ovat keskittyneet tiettyyn asiaan esimeriksi
        turvallisuuteen tai ohjelmistokehitykseen.
    </p> -->
    <div class="artikkelit">
    {% for artikkeli in artikkelit %}
        <div class="artikkeli">

            {% if artikkeli.kuva %}
                <img src="{{ artikkeli.kuva.url }}">
            {% endif %}
            <div class="artikkeliteksti">
            <h2 id="{{ artikkeli.otsikko }}"> {{ artikkeli.otsikko }}</h2>
            <p> {{ artikkeli.teksti }} </p>
            </div>

        </div>
    {% endfor%}
    </div>

{% endblock %}